version: '3.8'
services:
  backend:
    image: keeponherdin-backend
    restart: always
    environment:
      - DATABASE_HOSTNAME=db
    ports:
      - "8000:8000"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DEV_DB_USER}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
      - POSTGRES_DB=${DEV_DB}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#  db-test:
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=${DEV_DB_USER}
#      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD}
#      - POSTGRES_DB=${DEV_DB}
#    ports:
#      - '6543:6543'
volumes:
  db:
    driver: local