apiVersion: v1
kind: Service
metadata:
  name: keeponherdin-frontend
  labels:
    app: keeponherdin-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
      app: keeponherdin-frontend